### ISSUE TITLE
Article about this repo

### ISSUE THREAD

**Issue by Foxandxss** [auth0/angular2-authentication-sample#8]
Hey @mgonto and @gdi2290.

Is there any article in mind for this repository? I see one for the react + auth.

If not, I could tackle it for angular-tips. I want to start talking about angular 2 ASAP for my blog and I you know I really like JWT stuff.

Of course I would give the link and credits to this repo.

My plan is to explain a bit how Angular 2 works and build this app step by step.

Cheers.

**Comment by mgonto** [comment]
Hey 
Thanks for all the contributions. As a Patrick said, it won't work due to the router. 
Regarding the blog post, I'm already writing one about it, will be out next week :). 

Mobile mail. Excuse brevity and typos. 

On Sun, May 3, 2015 at 3:32 PM -0700, "Jesús Rodríguez Rodríguez" notifications@github.com wrote:

Hey @mgonto and @gdi2290.

Is there any article in mind for this repository? I see one for the react + auth.

If not, I could tackle it for angular-tips. I want to start talking about angular 2 ASAP for my blog and I you know I really like JWT stuff.

Of course I would give the link and credits to this repo.

My plan is to explain a bit how Angular 2 works and build this app step by step.

Cheers.

**Comment by mgonto** [comment]
But it'll be mostly about adding Auth. if you want to write one general about Angular2 with this repository that's fine for me :). 
Thanks!! 

Mobile mail. Excuse brevity and typos. 

On Sun, May 3, 2015 at 3:32 PM -0700, "Jesús Rodríguez Rodríguez" notifications@github.com wrote:

Hey @mgonto and @gdi2290.

Is there any article in mind for this repository? I see one for the react + auth.

If not, I could tackle it for angular-tips. I want to start talking about angular 2 ASAP for my blog and I you know I really like JWT stuff.

Of course I would give the link and credits to this repo.

My plan is to explain a bit how Angular 2 works and build this app step by step.

Cheers.

**Comment by Foxandxss** [comment]
Oh, well, that is good too :)

**Comment by Foxandxss** [comment]
Ah, new message. I could do that yes, I don't think it is going to hurt to have more information about Angular / JWT / auth0. Maybe I change the demo a bit to give something else, I don't know but my Angular 2 is still greenish.

**Comment by mgonto** [comment]
sounds great! 

Mobile mail. Excuse brevity and typos. 

On Sun, May 3, 2015 at 3:40 PM -0700, "Jesús Rodríguez Rodríguez" notifications@github.com wrote:

Ah, new message. I could do that yes, I don't think it is going to hurt to have more information about Angular / JWT / auth0. Maybe I change the demo a bit to give something else, I don't know but my Angular 2 is still greenish.
